---
title: "Statistics from SRA (ants)"
---

```{r}
dttm <- Sys.Date()

test <- FALSE
```


Last updated on `r dttm`.

---

This website contain statistics obtained from [# Sequence Read Archive (SRA) database](https://www.ncbi.nlm.nih.gov/sra).

For questions, please contact us [via email](contact.qmd).


___

# Number of datasets in SRA

```{r}
library(rvest)
library(dplyr)
library(ggplot2)

# Specify the URL of the webpage
url <- c("https://www.antwiki.org/wiki/index.php?title=Category:Extant_genus&pageuntil=Messor#mw-pages",
         "https://www.antwiki.org/wiki/index.php?title=Category:Extant_genus&pagefrom=Messor#mw-pages",
         "https://www.antwiki.org/wiki/index.php?title=Category:Extant_genus&pagefrom=Veromessor#mw-pages")

# Read the webpage and extract the ant species names
for (i in 1:length(url)) {
  page <- read_html(url[i])
  if (i==1) {
    genus_names <- page %>%
      html_nodes(paste0(".mw-category-group a")) %>%
      html_text()
  } else {
    foo <- page %>%
      html_nodes(paste0(".mw-category-group a")) %>%
      html_text()
    genus_names <- c(genus_names, foo)
  }
}

# Subset for test
if(test) {
  genus_names <- genus_names[1:2]
}


# for each genus name,
# - check the sra database to look for rnaseq datasets
npubs <- list()
for (i in 1:length(genus_names)) {
  
  db <- "sra"  # Sequence Read Archive (SRA) database
  query <- paste0(genus_names[i],
                  "[Organism] AND RNA-Seq[Strategy]")
  
  # Perform the search and fetch dataset IDs
  if(test) {
    how_many <- 10
  } else {
    how_many <- 10000
  }
  
  search_results <- rentrez::entrez_search(db, term = query, retmax = how_many)
  ids <- search_results$ids
  
  # how many unique datasets?
  npubs[[i]] <- length(ids)
  
}

genus.npubs <-
  data.frame(
    genus_name = genus_names,
    npubs = unlist(npubs)
  )

dat <- 
  genus.npubs |>
  # readRDS(
  #   "./ant_genus_rnaseq_datasets_7May23.Rds"
  # ) %>%
  as_tibble() |> 
  mutate(genus_name=as.character(genus_name)) %>% 
  mutate(genus_name2 = ifelse(npubs<10, "OTHER GENUS", genus_name)) %>% 
  group_by(genus_name2) %>% 
  summarize(npubs = sum(npubs, na.rm = T)) %>% 
  arrange(npubs)
# filter(genus_name2 != "others")


## Make table

dat |> 
  filter(
    npubs > 0
  ) |> 
  arrange(
    desc(npubs)
  ) |> 
  rename(
    `Genus Name` = genus_name2,
    `Number of SRA datasets found` = npubs
  ) |> 
  DT::datatable(
    caption = "Number of unique datasets in SRA database"
  )
```


## Distribution across ant genus

```{r fig.height=8, fig.width=6}
genus.lvls <- dat %>% pull(genus_name2)


dat %>% 
  mutate(genus_name2 = factor(
      genus_name2, 
      levels = genus.lvls
    )
  ) %>% 
  
  ggplot(aes(x=genus_name2, y=npubs)) +
  # geom_col(fill="grey10", width = .4) +
  geom_histogram(
    stat = "identity",
    size=.5, 
    fill="grey60", 
    col="white"
  ) +
  scale_y_log10() +
  labs(
    x = "",
    y = "Unique datasets\nin SRA database"
  ) +
  theme_minimal(16) +
  coord_flip()
# theme(axis.title.x = element_blank())
# theme(axis.title.y = element_blank())

```

